spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "root"
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true